# Generated by Django 3.0.7 on 2020-06-16 20:08

from django.db import migrations
import struct
from ..bbcdata import readFloat40, readRecord

def import_ingredients(apps, schema_editor):
    # Get the historical version of the models
    Ingredient = apps.get_model('recipe', 'Ingredient')
    Method = apps.get_model('recipe', 'Method')

    # Add methods
    f = open('./imports/methods.txt', 'r')
    m = 1
    for line in f:
        method = Method(method_num=m, description=line)
        method.save()
        m += 1

    # Add ingredients
    f = open('./imports/ingredients.dat', 'rb')
    data = bytes(f.read())
    i = 0
    value,i = readFloat40(data, i)      # Don't know what first number is
    while i + 5 < len(data):            # Ignore the last 5-byte number also
        record,i = readRecord(data, i)
        ingredient = Ingredient(
            name = record['Fruit'],
            variety = record['Variety'],
            acid = record['TA_pc'] * 10.0,
            sugar = record['Sugar_pc'] * 10.0,
            unferm_sugar = record['UnSugar_pc'] * 10.0,
            solu_solid = record['SoluSolid_pc'] * 10.0,
            body_to_acid = record['BodyToAcid_pc'],
            tannin = record['Tannin_pc'] * 10.0,
            pectin = record['Pectin'] == 'yes',
            pectolaise = record['Pectolaise'] == 'yes',
            redness = record['Redness'],
            brownness = record['Brownness'],
            starch = record['Starch_pc'] * 10.0,
            method = Method.objects.get(method_num=int(record['Method'])),
            liquid = 500.0 if record['Solid'] == 'yes' else 1000.0,
            suggest_max = record['SuggMax_g_gal'] / 4.55 )
        ingredient.save()

def remove_ingredients(apps, schema_editor):
    # Get the historical version of the models
    Ingredient = apps.get_model('recipe', 'Ingredient')
    Method = apps.get_model('recipe', 'Method')

    Ingredient.objects.all().delete()
    Method.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_method_method_num'),
    ]

    operations = [
        migrations.RunPython(import_ingredients,remove_ingredients)
    ]
