# Generated by Django 3.0.7 on 2020-06-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20200616_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='WineStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweetness', models.CharField(max_length=32)),
                ('colour', models.CharField(max_length=32)),
                ('grapes', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('alcohol', models.FloatField()),
                ('acid', models.FloatField()),
                ('tannin', models.FloatField()),
                ('solu_solid', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FileField(upload_to='')),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.LogEntry')),
            ],
        ),
        migrations.AddField(
            model_name='brew',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Image'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Image'),
        ),
    ]
