# Generated by Django 3.0.7 on 2020-06-17 14:02

from django.db import migrations
import csv

def import_winestyles(apps, schema_editor):
    # Get the historical version of the models
    WineStyle = apps.get_model('recipe', 'WineStyle')

    with open('./imports/wines.txt', 'r') as f:
        cf = csv.reader(f, delimiter=',', skipinitialspace=True)
        for i, vals in enumerate(cf):
            if i > 0:
                winestyle = WineStyle(
                    sweetness = vals[0],
                    colour = vals[1],
                    grapes = vals[2],
                    region = vals[3],
                    alcohol = vals[4],
                    acid = float(vals[5]) * 10.0,
                    tannin = float(vals[6]) * 10.0,
                    solu_solid = float(vals[7]) * 10.0
                )
                winestyle.save()

def remove_winestyles(apps, schema_editor):
    # Get the historical version of the models
    WineStyle = apps.get_model('recipe', 'WineStyle')
    WineStyle.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20200617_1357'),
    ]

    operations = [
        migrations.RunPython(import_winestyles,remove_winestyles)
    ]
