# Generated by Django 3.0.7 on 2020-06-17 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0006_auto_20200617_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('solid_small_units', models.PositiveSmallIntegerField(choices=[(0, 'kg'), (1, 'g'), (2, 'lb'), (3, 'oz')])),
                ('solid_large_units', models.PositiveSmallIntegerField(choices=[(0, 'kg'), (1, 'g'), (2, 'lb'), (3, 'oz')])),
                ('liquid_small_units', models.PositiveSmallIntegerField(choices=[(1, 'l'), (2, 'ml'), (3, 'gal (US)'), (4, 'gal (Imp)'), (5, 'fl oz (US)'), (6, 'fl oz (Imp)')])),
                ('liquid_large_units', models.PositiveSmallIntegerField(choices=[(1, 'l'), (2, 'ml'), (3, 'gal (US)'), (4, 'gal (Imp)'), (5, 'fl oz (US)'), (6, 'fl oz (Imp)')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
