# Generated by Django 3.0.7 on 2020-06-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liquid_large_units',
            field=models.PositiveSmallIntegerField(choices=[(0, 'l'), (1, 'ml'), (2, 'gal (US)'), (3, 'gal (Imp)'), (4, 'fl oz (US)'), (5, 'fl oz (Imp)')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liquid_small_units',
            field=models.PositiveSmallIntegerField(choices=[(0, 'l'), (1, 'ml'), (2, 'gal (US)'), (3, 'gal (Imp)'), (4, 'fl oz (US)'), (5, 'fl oz (Imp)')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='solid_large_units',
            field=models.PositiveSmallIntegerField(choices=[(0, 'kg'), (1, 'g'), (2, 'lb'), (3, 'oz')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='solid_small_units',
            field=models.PositiveSmallIntegerField(choices=[(0, 'kg'), (1, 'g'), (2, 'lb'), (3, 'oz')], default=1),
        ),
    ]
