# Generated by Django 3.0.7 on 2020-06-22 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20200618_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='style',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='recipe.WineStyle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='volume_l',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
