# Generated by Django 3.0.7 on 2020-07-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_auto_20200701_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='variety',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
