# Generated by Django 3.0.7 on 2020-08-03 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_auto_20200727_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='log_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brew',
            name='started',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='brew',
            name='updated',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
