# Generated by Django 3.0.7 on 2020-08-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_ingredient_default_qty_kg_per_l'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_solid',
            field=models.BooleanField(default=False),
        ),
    ]
